server:
  port: 16113

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller

# =========================================================
# Standard Spring Boot Logging Configuration
# =========================================================
logging:
  # 1. Enable logging to a file and specify the path and name.
  file:
    name: ./logs/ts-admin-route-service.log
  
  # 2. Set log levels for different parts of the application.
  level:
    # Set the default log level for all loggers to INFO (default in production)
    root: DEBUG
    
