name: Deploy Docker Images

on:
  push:
    - main
    - server_ci_cd

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Check
        run: echo "working runner"

      - name: Check current directory
        run: pwd

      - name: Set correct env for running the docker images in the Minikube
        run: |
          eval $(minikube docker-env)

      - name: Set file change permission to deployment folder
        run: |
          sudo chmod -R 777  deployment

